Maxquant anndata python conversion
czbiohub/mspipelines pull request #12
Opened 2022-12-13 16:59 UTC by KennethVerheggen

Created an initial conversion from R to python for maxquant output conversion to anndata

2022-12-20 07:52 UTC, rcannood requested changes
The functionality looks good to me! Happy to see you included a unit tests for the component! :+1: 

Can you take care of the following:

* Add an entry to the changelog
* Run a linter to fix code formatting
* Add type annotations to the functions
* Make the functions return a data frame as opposed to doing inplace replacements

2022-12-21 08:51 UTC, DriesSchaumont requested changes

2022-12-21 08:51 UTC, DriesSchaumont commented on src/convert/maxquant_to_h5ad/script.py
> +    dataframe = dataframe_old.copy(deep=True)
Use a for-loop for this: 
```python
from_to = {
    "+": ("and", False),
    "%": ("pct", False),
    " ": ("_", False),
    "[^a-zA-Z0-9_]*", "", regex=True
}
new_columns = dataframe.columns
for old, (new, use_regex) in from_to.items():
    new_columns = new_columns.str.replace(old, new, use_regex=use_regex)
new_columns = new_columns.lower()

```

2022-12-21 08:51 UTC, DriesSchaumont commented on src/convert/maxquant_to_h5ad/script.py
> +    for column in dataframe.columns:
pandas has a function to iterate columns:
```python3
for column_name, column in dataframe.items():
    column.replace([False, True], [0, 1], inplace=True)
```

2022-12-21 08:51 UTC, DriesSchaumont commented on src/convert/maxquant_to_h5ad/script.py
> +summary_nt = summary[summary["Raw file"].str.contains("Total") == False]
Does 
```summary[! summary["Raw file"].str.contains("Total")]```
or 
```summary[not summary["Raw file"].str.contains("Total")]```
work?
If so, I would replace with one of these options

2022-12-21 10:34 UTC, KennethVerheggen commented on src/convert/maxquant_to_h5ad/script.py
> +    dataframe = dataframe_old.copy(deep=True)
Adapted to use a for loop

2022-12-21 10:34 UTC, KennethVerheggen commented on src/convert/maxquant_to_h5ad/script.py
> +    for column in dataframe.columns:
Adapted to use the pandas iterator

2022-12-21 10:35 UTC, KennethVerheggen commented on src/convert/maxquant_to_h5ad/script.py
> +summary_nt = summary[summary["Raw file"].str.contains("Total") == False]
Tried with various options, none work save for the original one thus far...

2022-12-21 10:50 UTC, merged