Alternative maxquant
czbiohub/mspipelines pull request #2
Opened 2022-11-22 13:37 UTC by KennethVerheggen

Please verify this version meets proposed changes

2022-11-23 04:36 UTC, rcannood commented on src/maxquant/maxquant/script.py
> +                 )
fix indentation

2022-11-23 04:39 UTC, rcannood commented on src/maxquant/maxquant/templates/root.xml.jinja
> +        {% block fastafileinfo scoped required %}{% endblock %}
It's a nice proof of concept but I don't think using a block with a second file is needed at this stage. I suggest simply copying the contents of the block into the `root.xml.jinja`.

@DriesSchaumont @Kenneth-DI What do you think?

2022-11-23 04:45 UTC, rcannood requested changes
This looks so much better :heart_eyes: 

@KennethVerheggen Could you merge the main branch into this branch so that it can be merged back into main?

2022-11-23 04:45 UTC, rcannood commented on src/maxquant/maxquant/templates/root.xml.jinja
> +        {% block fastafileinfo scoped required %}{% endblock %}
It's a nice proof of concept but I don't think using a block with a second file is needed at this stage. I suggest simply copying the contents of the block into the `root.xml.jinja`.

@DriesSchaumont @KennethVerheggen What do you think?

2022-11-23 04:45 UTC, rcannood commented on src/maxquant/maxquant/script.py
> +                 )
fix indentation of the `)`

2022-11-23 08:36 UTC, DriesSchaumont commented on src/maxquant/maxquant/templates/root.xml.jinja
> +        {% block fastafileinfo scoped required %}{% endblock %}
Sure, lets do that. Opening a second file to see the contents is a pain. Could be useful in the future where we need to add different xml blocks depending on parameters. But for now lets not split files

2022-11-23 09:42 UTC, KennethVerheggen commented on src/maxquant/maxquant/templates/root.xml.jinja
> +        {% block fastafileinfo scoped required %}{% endblock %}
Will replace the extra file and integrally put the block in the root xml !

2022-11-24 15:43 UTC, DriesSchaumont commented
LGTM  @rcannood

2022-11-24 15:43 UTC, DriesSchaumont approved these changes

2022-11-25 14:23 UTC, merged